name: PR Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: |
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --parallel